services:
  kafka_broker_controller_1:
    image: confluentinc/cp-kafka:7.7.1
    container_name: kafka_broker_controller_1
    ports:
      - 9092:9092
    expose:
      - 9093
    environment:
      CLUSTER_ID: 4645820b-7d6b-45c3-8122-b074b343ef23
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_LISTENERS: EXTERNAL://localhost:9092,INTERNAL://localhost:9093
      KAFKA_ADVERTISED_LISTENERS: EXTERNAL://localhost:9092
      KAFKA_CONTROLLER_LISTENER_NAMES: INTERNAL
      KAFKA_INTER_BROKER_LISTENER_NAME: EXTERNAL
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@localhost:9093
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_NUM_PARTITIONS: 3

#  kafka_init_topics:
#    image: confluentinc/cp-kafka:7.7.1
#    container_name: kafka_init_topics
#    depends_on:
#      - kafka_broker_controller_1
#    entrypoint: [ '/bin/sh', '-c' ]
#    command: |
#      "
#      kafka-topics --bootstrap-server localhost:9093 --list
#
#      echo -e 'Creating kafka topics'
#      kafka-topics --bootstrap-server localhost:9093 --create --if-not-exists --topic numbers --replication-factor 1 --partitions 5
#
#      echo -e 'Successfully created the following topics:'
#      kafka-topics --bootstrap-server localhost:9093 --list
#      "