micronaut:
  application:
    name: consumer
  server:
    port: 8081

kafka:
  bootstrap:
    servers: localhost:29092 # TODO make configurable

# Custom configs
numbers:
  max-number-allowed: 9223372036854775807 # Assumes that Long.MAX_VALUE is the max allowed value to check for prime number.
  kafka:
    topic-name: numbers