micronaut:
  application:
    name: consumer
  server:
    port: 8081

kafka:
  bootstrap:
    servers: localhost:29092 # TODO make configurable

# Custom configs
numbers:
  kafka:
    topic-name: numbers