micronaut:
  application:
    name: producer

kafka:
  bootstrap:
    servers: localhost:29092 # TODO make configurable


# Custom configs
numbers:
  kafka:
    topic-name: numbers
  generator:
    delay: ${NUMBER_GENERATOR_DELAY:2000ms}
    max-number: ${NUMBER_GENERATOR_MAX_NUMBER:100}