micronaut:
  application:
    name: producer

kafka:
  bootstrap:
    servers: ${KAFKA_BOOTSTRAP_SERVER:`localhost:29092`}

# Custom configs
redis:
  server: ${REDIS_SERVER:`redis://localhost:6379`}

numbers:
  output-file-name: ${GENERATED_NUMBERS_FILE_PATH:`generated_numbers.csv`}
  kafka:
    topic-name: numbers
  generator:
    delay: ${NUMBER_GENERATOR_DELAY:200ms}
    max-number: ${NUMBER_GENERATOR_MAX_NUMBER:100}